language:
  node_js
node_js:
  - node
  - lts/*
install:
  - npm install
  - npm install -g codecov nyc
script:
  - nyc npm test
after_success:
  - nyc report --reporter=lcov > coverage.lcov
  - codecov
